spring:
  application:
    name: kokomen-notification-internal
  profiles:
    include:
      - domain
      - common
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

---
# local profile
spring:
  config:
    activate:
      on-profile: local
