spring:
  profiles:
    include: domain
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

---
# local profile
spring:
  config:
    activate:
      on-profile: local
