# Common configuration for all profiles
---
# local profile
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: kokomen-local-redis
      port: 6379

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: kokomen-redis-dev
      port: 6379
