name: CD API DEV

on:
  pull_request:
    branches: [ develop ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: develop
          filters: |
            api:
              - 'api/**'

  build-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql-redis.sh
        run: chmod +x run-test-mysql-redis.sh
        working-directory: ./domain

      - name: Run test mysql redis script
        run: ./run-test-mysql-redis.sh
        working-directory: ./domain

      - name: Test & Build api only
        run: ./gradlew :api:build

      - name: Sign in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/amd64 --no-cache -t samhap/kokomen-notification-api:dev .
        working-directory: ./api

      - name: Push the Docker Image to Dockerhub
        run: docker push samhap/kokomen-notification-api:dev
        working-directory: ./api

  deploy-api:
    needs: build-api
    runs-on: [ self-hosted, dev-notification ]
    steps:
      - name: Stop existing container
        run: sudo docker rm -f kokomen-notification-dev-api || true

      - name: Remove old API Docker image
        run: |
          if sudo docker images samhap/kokomen-notification-api:dev -q | grep -q .; then
            sudo docker rmi -f samhap/kokomen-notification-api:dev || true
          fi

      - name: pull docker compose yaml files
        working-directory: /home/ubuntu
        run: |
          [ -d kokomen-notification ] || git clone --filter=blob:none --no-checkout https://github.com/samhap-soft/kokomen-notification.git
          cd kokomen-notification
          git sparse-checkout init --cone
          git fetch origin feature/#10
          git checkout feature/#10
          git sparse-checkout set docker/dev
          git pull origin feature/#10

      - name: Docker Image pull
        run: sudo docker pull samhap/kokomen-notification-api:dev

      - name: Docker run
        working-directory: /home/ubuntu
        env:
          MYSQL_ROOT_PASSWORD_DEV: ${{ secrets.MYSQL_ROOT_PASSWORD_DEV }}
          SPRING_DATASOURCE_USERNAME_DEV: ${{ secrets.SPRING_DATASOURCE_USERNAME_DEV }}
          SPRING_DATASOURCE_PASSWORD_DEV: ${{ secrets.SPRING_DATASOURCE_PASSWORD_DEV }}
        run: |
          export HOSTNAME=$(hostname)
          cd kokomen-notification/docker/dev
          sudo -E docker compose -f docker-compose-dev.yml up -d kokomen-notification-dev-api kokomen-notification-mysql-dev
