name: CI INTERNAL TEST

on:
  pull_request:
    branches: [ main, develop ] # TODO: develop-internal 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql-redis.sh
        run: chmod +x run-test-mysql-redis.sh
        working-directory: ./domain

      - name: Run test mysql redis script
        run: ./run-test-mysql-redis.sh
        working-directory: ./domain

      - name: Test & Build internal only
        run: ./gradlew :internal:build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
          files: ${{ github.workspace }}/internal/build/test-results/**/*.xml
          seconds_between_github_reads: 1.0
          seconds_between_github_writes: 3.0
          secondary_rate_limit_wait_seconds: 90.0

      - name: When test fail, comment on that code
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ github.workspace }}/internal/build/test-results/**/*.xml
          token: ${{ github.token }}
